version: '3.8'

services:
  
  # nginx:
  #   image: my-nginx
  #   build:
  #     context: nginx
  #     dockerfile: ./Dockerfile
  #   container_name: my-nginx
  #   restart: unless-stopped
  #   ports:
  #   - 80:80
  #   networks:
  #     - vendingNetwork

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vending_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./vending-dump.sql:/docker-entrypoint-initdb.d/vending-dump.sql
    ports:
      - "5432:5432"
    restart: unless-stopped  
    networks:
    - vendingNetwork

  vending:
    image: vending
    container_name: vending
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: vending
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
    - vendingNetwork

  vending-client:
    image: vending-client
    container_name: vending-client
    build:
      context: vending-client
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
    - vendingNetwork

networks:
  vendingNetwork:
    driver: bridge